### ISSUE TITLE
Quick Forms: Filter assets by field location

### ISSUE THREAD

**Issue by aislinnpearson** [Rothamsted-Ecoinformatics/farm_rothamsted#172]
An issue that several of the farm team have raised is that it is quite hard to find plant assets on the quick forms because the list is so long. They have asked if we could please add 'Field' to the Drilling, Spraying, Fertiliser, Field Operations and both Harvest forms, and use this field to display a filtered list of assets associated with that field.

They have asked that this is a priority as searching can be quite time consuming and it makes a big difference now they are using the tablets in the field.

**See also duplicate issue #260**

**Comment by aislinnpearson** [comment]
Following on from the call on 03 May 2022:

We agreed that the initial solution for this is to create a search box on the assets quick form which allows you to search and filter assets based on **one or more** locations. This will be added to FarmOS core as it addresses an issue raised there as well (@paul12/ @mstenta feel free to include a link here if you want to document the link between projects - I couldn't find it).

This will then replicate the process for the experiments module in terms of searching for assets via a plan/ location.

**Comment by paul121** [comment]
I'm going to close this issue, we've implemented #260 in its place. They are *very* similar but not necessarily duplicates. In this issue we had proposed adding a "Location" filter to farmOS views of assets. This way you could filter assets by location from many different places in farmOS, including on the pages that let you "prepopulate" which assets you would like to reference in a quick form.

I believe @mstenta had started a branch to implement this but it is not quite done. This is a bit of technical challenge to implement due to the complex nature of the farmOS location logic.

In #260 we're changing quick forms so users go through a two-step process to select assets: first search for location(s), then complete checkboxes for asset(s) in those location(s).

**Comment by aislinnpearson** [comment]
Sounds good tome. Thanks @paul121
