### ISSUE TITLE
Display validation error message in quick forms with vertical tabs

### ISSUE THREAD

**Issue by aislinnpearson** [Rothamsted-Ecoinformatics/farm_rothamsted#176]
Josh has pointed out that when the quick forms won't submit (possibly because one of the required fields hasn't been filled in) but there is no error message to say which field has been left out. He is having particular problems with the spraying quick form which won't submit even though all the fields are populated. I said I would have a look into this separately with him to see if it is a different error.

**Comment by mstenta** [comment]
@aislinnpearson I actually wonder if this is related to the bug reported this morning - which was causing the quick forms to display an error when you tried to load them. Maybe worth trying to submit the spraying form again now that that is fixed?

**Comment by aislinnpearson** [comment]
Thanks @mstenta. I just double checked now and I could submit a form, but I'll still ask Josh to do the one he has.

I did try leaving out some of the required fields but the form wouldn't submit (with no error message) so I'll keep the issue live for now, but great to know we've got one element of Josh's problem solved!

**Comment by aislinnpearson** [comment]
Comments from our discussion on 03 May 2022: @paul121 pointed out that HTML 5 validation doesn't integrate with vertical tabs: you can display an error message but it won't take you to the tab where the data is missing. @aislinnpearson said this would be fine - it is at least a step in the right direction.

@mstenta also wanted to clarify that the problem only happens when data is missing from required fields, which @aislinnpearson confirmed is correct.

**Comment by paul121** [comment]
Ah interestingly we get a console error when this happens:

```
An invalid form control with name='crop_variety[]' is not focusable.
An invalid form control with name='seed_rate[value]' is not focusable.
An invalid form control with name='drilling_rate[value]' is not focusable.
An invalid form control with name='time_taken[hours]' is not focusable.
```

**Comment by paul121** [comment]
Okay! Happy to report the fix for this came out on the easier side :smile: There was two parts:

1) Disable HTML5 validation.

This can be done by simply adding the `novalidate` attribute to the `form` element:

```php
    $form['#attributes']['novalidate'] = 'novalidate';
```

The result of this is that red error messages will be generated when required values are not submitted. The individual fields are also highlighted in a red border.

2) Open vertical tabs that contain fields with validation issues.

This was a bit more challenging, but following this comment from a Drupal core issue I was able to put together a simple JS that does this quite easily: https://www.drupal.org/project/drupal/issues/2911932#comment-13646662 Of course we can only open one tab at a time, so this will open the tab with the first invalid field. Another trick to this was making sure the JS behavior only selects fields that have been flagged as having an error, else it would switch tabs after uploading a file, but before the form was submitted.

![Screenshot from 2022-05-06 15-21-22](https://user-images.githubusercontent.com/3116995/167223864-cd1f0b10-51aa-40e3-8225-b247a095ec8d.png)

**Comment by aislinnpearson** [comment]
HI @paul121,

This looks great. I did have one question to clarify: does this mean that if you get to the end of the form (Job Status tab) you see the error messages, and then have to manually navigate to the Operation tab? If so that works for me. Thanks so much for sorting it.

**Comment by paul121** [comment]
@aislinnpearson nope, if you get the end of the form and submit it will automatically open the first tab that has an error

**Comment by aislinnpearson** [comment]
Even better!
