### ISSUE TITLE
Harvest Quick Forms: displaying both field and storage locations

### ISSUE THREAD

**Issue by aislinnpearson** [Rothamsted-Ecoinformatics/farm_rothamsted#192]
The farm team at North Wyke have now had the opportunity to look at the harvest quick forms in detail and have made the point that the Harvest (trailer/ bale weights) quick form would ideally include two locations: the field which was harvested (so the harvest record remains associated with that field) and the location the asset was moved to (the silage clamp/ storage bay/ grain silo, so you also have a full record of where the asset currently is and what was stored there in previous years). Currently it only displays one location: the site it was moved to.

Tagging issue #185 in case the two are related.

**Comment by paul121** [comment]
This is actually more related to #183 - that issue will start adding the asset's current location to all logs created via quick forms. So when submitting the Harvest (trailer/bale weights) quick form both the storage location and the current location(s) of the selected plant asset(s) will be saved in the harvest log's location field.

We chatted today specifically about how it might be weird to reference two locations in the harvest log's location field for this; certainly having a structure asset as the only location doesn't make sense, because the harvest happened in a field, but the resulting harvested product was moved to the structure asset storage location. Adding the field location here helps clarify this. **_We agreed that saving both the field location and storage location in the harvest location is a good convention in the short term._** Because these are created via a quick form it is consistent and capable of being migrated to a new convention in the future.

In the long term, there seems to be two options:
1) When harvesting from a plant asset, a new "product" asset of some type should be created. This resulting product would represent what was harvested from the field, and because it is a separate asset, can be moved separate of the plant asset into the storage location via a movement log. Introducing a new "product" asset to the mix could add a lot of complexity but is the "most accurate" way to represent what is happening in the real world.
2) Another approach is to use inventory logs to adjust the inventory of the final storage location. We are already creating various quantities on the harvest log, so it would just be a matter of adjusting one of these quantities (the one that most accurately represents the total harvest) to be an inventory adjustment. Technically this could be a pretty simple change, but introduces more complexity for the farm team to understand and manage the inventory in these storage locations.

@aislinnpearson @mstenta this is a quick summary of our conversation today, please add/clarify if you think I missed anything!

**Comment by mstenta** [comment]
Now that this is closed, do we need a new issue for adding the "Storage location" field? (Ignore this if that's already covered somewhere, or if @paul121 or @aislinnpearson are already planning on opening this - just wanted to make sure it didn't get lost!)

**Comment by paul121** [comment]
Thanks for mentioning this @mstenta - I was confused by your comments earlier but didn't get a chance to ask.

Maybe to clarify: right now the harvest (trailer/bale weights) quick form has a `Storage location` field that loads the list of `storage_location` structure assets. This asset reference is saved into the harvest log `location` field when the quick form is submitted.

I don't think we need to add a second `storage_location` field on harvest logs.. I think the type of asset distinguishes the meaning when multiple assets are saved in the same log location field.

**Comment by mstenta** [comment]
Oh. I thought we had decided on the call to have two fields on the log. I must have misunderstood.

I don't like the idea of mixing both locations in the same field, personally. Even though they are different types there is ambiguity. Whoever is looking at this in the future (maybe it won't be us!) will have to be aware of this "implicit" distinction.

Perhaps if these "Rothamsted-specific conventions" were very explicitly documented somewhere (and managed in a way that allows them to be changed/updated as things/people change), then it would be OK. But it still feels like a problem waiting to happen.

**Comment by paul121** [comment]
Ah okay. Well we certainly can add another field! That would make this convention more explicit. But also is another thing at the db/storage level to maintain.

Before we create another field would it be better to figure out if we want to go the product asset or inventory adjustment route instead?

**Comment by mstenta** [comment]
> That would make this convention more explicit. But also is another thing at the db/storage level to maintain.

Yea that's basically what I was thinking through on the call - probably not out loud in a very intelligible way. :sweat_smile: 

> Before we create another field would it be better to figure out if we want to go the product asset or inventory adjustment route instead?

It's a good question.

If there is urgency, then I suppose we could just leave it as-is (store both in the same field), but try to figure out a next step ASAP so that we can migrate to it soon. As you said, having the two location types (plot/plant vs structure) available gives us something to automate that migration on. I would just like to see it done before it gets forgotten, otherwise it's leaving a bit of a mess for future data managers.

**Comment by aislinnpearson** [comment]
Hi Both,

So having had the chance to think this through, here is my opinion (for further discussion as no doubt I am missing some of the development subtilties here and want to be very careful creating work if we don't have to) but I do think it is worth maintaining another field _because_ it is so explicit. 

Here are a couple of use cases I can think of for harvest and inventory adjustments:

1. **Sale of harvested goods:** seed taken off in multiple trailer loads and put in a storage location _along with_ the same crop from different fields. Parts of one asset are combined with others to create new, larger asset(s) sold to a different producer (who might want to know which fields were cropped). You need to know who you sold it to, and for how much plus retain any documents associated with crop quality, etc.
2. **Seed/ grass harvest used for livestock:** taken off in multiple trailer loads and put in a storage location _along with_ the same crop from different fields. One asset is combined with others to create a new, larger asset which is incrementally fed to livestock. Seed or grass in this instance might also have inputs associated with it (e.g. silage additives). 
3. **Seed is used for propagation:** farm-saved seed is rare but a growing use case and we do it for the experiments. Seed is kept separate or stored only with the same variety to make sure the variety characteristics remains intact and then (ideally but not always) referenced in a future drilling log.
4. **There is no forward planning:** The crop failed. It is put on the compost heap. You forget about it until one day you decide to do something with it and need to know what was added to it. Or you might burn it. This is rarely thought of as a storage location - more an end location. 
5. I can also see a situation where some farms simply wouldn't bother with inventory adjustments, regardless of where the crop ends up. They know how much they have, and that is enough for them - anything else feels like an administrative burden.

What strikes me about this is that you can't remove the growing location that the asset comes from because, for each growing location, want to be able to trace back the assets (and logs) associated with it. In the UK we also need this for legal reasons (contamination, leaching, etc). In every instance you also want to know where the asset ended up (which may be more than one location if it is split between two barns for example), but the way you would want to implement any inventory adjustments would be integrated is very variable and quite a big development step in itself as we'd need to link documents and activities to those storage assets. To my mind decoupling storage location from an inventory adjustment is actually a good thing and offers more flexibility, as well as less development work? But as I say, this is just a user perspective. I don't fully understand what that entails for you from a maintainer's perspective.

As for your comment here @mstenta 

> Perhaps if these "Rothamsted-specific conventions" were very explicitly documented somewhere (and managed in a way that allows them to be changed/updated as things/people change), then it would be OK. But it still feels like a problem waiting to happen.

I couldn't agree with you more. @paul121 also requested this and I am making a bit of time each week (on a Tuesday :)) to do exactly that. There is a related issue here: #187

**Comment by aislinnpearson** [comment]
Following on from the above comment we discussed this further on our call on the 01 June 2022, and agreed the following.

The harvest quick form already has a storage location (which references a building asset with the type "storage location"). However, in the current implementation, this replaces the existing field location. On the call we agreed that crop assets could have two locations: the field location and the storage location. This requires creating a new data field harvest log for storage location. This maintains the history of records associated with an asset, a field location and a storage location. 

We also agreed that the storage location would be required on the Harvest (Trailer/ Bale Weights) quick form but optional on the harvest log form.

The new data field will be a Rothamsted specific convention.

**Comment by aislinnpearson** [comment]
HI @mstenta, @paul121,

I was looking through the quick forms today and noticed that the harvest storage location has been removed from the quick forms. 

@mstenta you mention adding the data field to the quick form [here](https://github.com/Rothamsted-Ecoinformatics/farm_rothamsted/issues/192#issuecomment-1136525055) and we obviously impleneted it because it is referenced [here](https://github.com/Rothamsted-Ecoinformatics/farm_rothamsted/issues/192#issuecomment-1148466978) and we have logs with storage locations at Harpenden and North Wyke (Brooms was updated after last year's harvest), but I can't find the specific issue - which to my mind means that in future we should definitely be documenting minor changes like this as we did with issue #397 

So re-opening this to ensure we discuss it on Tuesday, but I'm also aware there might be a more relevant issue to re-open that I am not seeing.

**Comment by paul121** [comment]
I see that the Harvest (Trailer/Bale weights) quick form does have a storage location under "operations". But the Harvest (Combine and Forage) quick form does not have a storage location option. Would you like to add it on both? If so could you open a new issue?

I may have only added it to Trailer/Bale weights since the issue description above seemed to suggest only one needed it:

> The farm team at North Wyke have now had the opportunity to look at the harvest quick forms in detail and have made the point that the Harvest (trailer/ bale weights) quick form would ideally include two locations:

![Screenshot from 2023-05-04 08-56-18](https://user-images.githubusercontent.com/3116995/236274625-6bf9f7c2-7f10-44e0-9876-471d77356bbe.png)

**Comment by aislinnpearson** [comment]
Following further discussion we decided to leave this as it is
