### ISSUE TITLE
Add form field to change the assets current location

### ISSUE THREAD

**Issue by paul121** [Rothamsted-Ecoinformatics/farm_rothamsted#196]
As a follow up to our discussion around #185. We would like to make it easier to re-assign the asset's current location.

We discussed today adding a "Current location" field to the edit tab on the asset. When submitted this would automatically create a movement log to set the asset's current location. This was a feature we had in farmOS v1.

**Comment by paul121** [comment]
I've got this working here: https://github.com/Rothamsted-Ecoinformatics/farm_rothamsted/pull/199#issue-1253075156

This approach of adding fields to the edit form is rather hacky. It does work, but I think there would be issues implementing this as a more general solution. I must admit this is likely the *easiest* solution from a users perspective... but as we discussed it is a bit misleading as well. I added this description to try and clarify what this means:  "The current location of the asset. Changing this value will update the assets current location with a new movement log. Latest movement log: {link to log}" @aislinnpearson what do you think?

I'd like to encourage the intentional approach of changing location via the "Move asset" action. Ideally future work could be towards making the "Move asset" action available on individual asset pages as @mstenta described in our call, but for now this is a quick fix.

**Comment by aislinnpearson** [comment]
Hi @paul121,

Thanks for this. 

I think the important thing from a user perspective is that you can go to the edit page for a plant asset, see it's current location and move it easily - but I agree with you and @mstenta that it is important that it is also important that the user understands that what they are doing is creating a movement log and _not_  just assigning a new location. 

The way I was picturing it in my head is that the current location would be a reference field rather than a field you can edit - basically displaying it in the same way that it is when you go to view a plant asset:

![image](https://user-images.githubusercontent.com/16349781/171152474-2ce0714b-6f48-4b9e-984d-9067ffee01bf.png)

And under that we would have a 'Move asset' button with a slightly amended version of your description.

 "This is the current location of the asset. To change the asset's current location you need to create a new movement log. Latest movement log: {link to log}"

If I am correct, that is what @mstenta was suggesting and it's only just now that I have wrapped my head around it. I do think that would be the most elegant solution, because then the option to move multiple assets at once would also make sense. And if you accidentally put it in the wrong place, you'd know to edit the movement log itself.

The other thing I wanted to clarify is: are we creating a movement log as soon as the commercial asset is created? Looking at the 2.3 Platformish site I assume that we are, and just to confirm I think it should stay that way (but need to create a date field for the date the asset was created - see #201)

I know that the farm team are really pushing for this location field, but I think that we should implement the general solution before pushing it to the Rothamsted instance. Especially if you want to use this as a test bed for that general solution. I do feel really bad that we are getting you to recode this multiple times over though @paul121. Thanks for sticking with me and making sure we get it right though.

**Comment by aislinnpearson** [comment]
Following on from the call on the 01 June 2022, we agreed that we would implement the solution as above, with the location displayed and a 'move asset' button which is accompanied by the above description.

We agreed we would put the edit button with the description in two places on the plant assets:
1. on the plant asset page, underneath where the current location is already listed
2. display the current location as above on edit page for the plant asset, and add the 'move' button plus description underneath the current location 

We agreed that the first would be a FarmOS convention, added to the core module, and the second a Rothamsted specific convention which we would trial in our instance. @paul121 suggested we could implement the latter by using the field formatter as the default and then switch it off.

**Comment by paul121** [comment]
> We agreed that the first would be a FarmOS convention, added to the core module, and the second a Rothamsted specific convention which we would trial in our instance.

I will start working on number 2 tomorrow to have it included with 2.3.0. It will take more time to get number 1 ready and shipped with a new version of farmOS core.

>  @paul121 suggested we could implement the latter by using the field formatter as the default and then switch it off.

Just to clarify this would be for number 1 - *I think* we could implement this by adding a field formatter for the current location and include a setting to optionally display this "Move asset" button on the asset page.

**Comment by aislinnpearson** [comment]
Sorry @Paul. My misunderstanding! Do you want me to create a new issue for 2, so we can use this for 1 and close it when 1 is complete?

**Comment by paul121** [comment]
I created a follow up issue for part 1 since this issue was largely related to part 2, and it allows us to start fresh :-) #217

**Comment by paul121** [comment]
![Screenshot from 2022-06-13 13-10-57](https://user-images.githubusercontent.com/3116995/173626186-47af5125-fda5-412b-9805-4d98cf726a3a.png)
