### ISSUE TITLE
Harvest (Combine/ Forage Harvester) Quick Form: convert quick form to an activity log

### ISSUE THREAD

**Issue by aislinnpearson** [Rothamsted-Ecoinformatics/farm_rothamsted#210]
Following discussion on the 07 June and in #203 we agreed that the Harvest (Combine/ Forage harvester) quick forms would be converted to activity logs. This applies to the base code, as well as any new harvest records which have been submitted since we switched over to FarmOS version 2.x (April 2022). Logs from before this period will be in the old format which recorded only a single value for harvest, and as such there will only be one log associated with each asset.

**Comment by paul121** [comment]
Hey @aislinnpearson there's one issue with converting this to an activity log: right now we accept a harvest lot number on the combine form which is saved directly to the harvest `log.lot_number` field. Activity logs don't have a `lot_number` field, so we would need to save this to the `notes` for now.

**Related:** the trailer and bales harvest form *does not* request a harvest lot number from the user, but it seems that maybe it should?

I think there could be value in having both the combine & trailer harvests both submitted as harvest logs and be linked by the same `lot_number`. The only difference is that they would have different quantity labels for their relevant quantities: combine harvests would have the "Yield estimate" (tbd in #193) and trailer harvests have "Nett weight" quantities.

I believe our primary motivation to change the combine harvest form from a harvest log to an activity log is to make it easier to sum the total weights, because all of the harvest logs would in theory be from the "trailer and bale" quick form and we could simply sum all the `weight` quantities. This is convenient, but I want to note that other harvest logs *could* be created outside of the quick forms, so there *should always* be some logic when summing up the total harvest weights to only sum the values that are needed.

**_In fact this logic would be needed right now (!)_** as we are recording at minimum 3 weight quantities for each trailer harvest: Trailer tare, Gross weight, and Nett weight. The logic would need to sum _only_ the Nett weights, not every weight quantity. Additionally, having the combine harvest connected to the trailer harvest(s) by a lot number would make it easier to compare the "Yield estimate" to the actual yield if this kind of comparison was ever needed.

In #193 a request to make requesting quantities by their label easily available via the API:
> but Had asked that we please standardise it so that it is easily accessible through the API.

Here is an API request that only returns harvest logs with a `Nett weight` quantity associated with asset ID 28 https://rothamsted.ddev.site/api/log/harvest?filter[quantity.label]=Nett%20weight&filter[asset.meta.drupal_internal__id]=28

**Comment by paul121** [comment]
On the call today - agreed we don't need to change this to an activity log! @aislinnpearson noted that maybe we could have custom logic to generate the harvest lot numbers as well - something like plant asset name/id + year/date.
