### ISSUE TITLE
Commercial Asset Quick Form: Add harvest year

### ISSUE THREAD

**Issue by aislinnpearson** [Rothamsted-Ecoinformatics/farm_rothamsted#229]
Our farm manager asked if we could please change the automatic naming of the so they read [Harvest Year] [Field]: Crop [Variety]. Currently it reads "[Season] [Field]: Crop [Variety]".

To achieve this we would probably want to include an additional data field for harvest year, but I'm not entirely sure what form this should take. Possibly a subset of the seasons taxonomy as we would also want options for 'Not Applicable', for example when creating multi-year assets for energy crops, grassland or woodland.

**Comment by paul121** [comment]
As we discussed, we'll start by using the a "Harvest year" hierarchy in the seasons taxonomy. The big motivation for doing this is so that assets will be linked to the same term, allowing the user to see "all plant assets in harvest year X" from the taxonomy page.

Technically, we'll need to add a required harvest year question to the commercial asset quick form. The options will be child terms of the "Harvest year" season parent term. On submission we need to include harvest year in the plant asset name, as well as the plant asset season (this is a muli-value field!).

**Comment by paul121** [comment]
@aislinnpearson I would suggest adding a `description` to these "Harvest year" season taxonomy terms. It may be confusing to tell the difference between a "drilling" season and a "harvest year" season since the term names are just the year. But including a description will explain this as soon as you click through to view either of the terms.

![Screenshot from 2022-08-05 08-33-31](https://user-images.githubusercontent.com/3116995/183111234-a833431a-6a2b-4f69-b09e-531869be29cc.png)

**Comment by aislinnpearson** [comment]
Agreed.
