### ISSUE TITLE
Quick Forms: adding equipment to multiple groups

### ISSUE THREAD

**Issue by aislinnpearson** [Rothamsted-Ecoinformatics/farm_rothamsted#258]
HI @mstenta, @paul121 

I noticed a new issue today which might be a bug, or it might just be me using the software incorrectly.

We have an equipment asset of 'By hand' which we use for exceptions in the quick forms. For example, if you are harvesting by hand your tractor is 'by Hand' and your trailed equipment is 'none'.

I want to assign this asset none to multiple groups so we can use it across multiple quick forms. To do this I find the asset, scroll to the bottom of the page and select the function 'group', This takes me to another window where I can either give a date for the time the asset is moved or mark it as already moved. If I mark it as already moved, the new group is added but the old group disappears. If I don't select a date, then the old group remains but the new one isn't added.

Could you let me know where I am going wrong? It's getting in the way of the Farm Team being able to submit some of their logs...

Thanks so much!

**Comment by paul121** [comment]
Hey @aislinnpearson yes I believe you experiencing the expected behavior. An asset's current group membership relies on its most recent group membership log. So if you want to assign to multiple groups, you need a group membership log which references multiple groups.

If you are updating an asset that is already a member of one or more groups, the new group membership log needs to include those groups it is already a member of if the asset should continue to be a member of those groups. Maybe it would be nice if the group membership page displayed what group(s) the asset is currently in and included a button to "include existing group membership" or something. Kind of how the flags are "append or replace".

Obviously we aren't using group membership as it was really designed for.. but hope that helps. Let me know if ya have questions

**Comment by paul121** [comment]
The group membership logic is documented here, perhaps we should include some explanation of the use case of an asset being in multiple groups: https://farmos.org/model/logic/group/

**Comment by aislinnpearson** [comment]
Ah I see! It works the same way the movement logs work. Got you. Thanks @paul121!
