### ISSUE TITLE
Feature Enhancement: Add 'Asset' to Quantities page

### ISSUE THREAD

**Issue by aislinnpearson** [Rothamsted-Ecoinformatics/farm_rothamsted#281]
Following on from issue #158 I was wondering if we could please add 'Asset' to the list of search terms under 'Quantities'. I have a couple of scientists who would like to download CSVs for their experiments but it's currently quite difficult to search by specific assets.

@paul121 I think one of our scientists would be grateful if we could get this sorted in the next couple weeks. Do you think it is something we could add to the current milestone?

![image](https://user-images.githubusercontent.com/16349781/186700563-2667d873-a5da-4be3-bccc-9612d68c0213.png)

**Comment by paul121** [comment]
I have created a pull request to farmOS core for this: https://github.com/farmOS/farmOS/pull/569

**Comment by paul121** [comment]
This was included in the farmOS 2.0.0-beta7 release! It should land on a Rothamsted site near you soon :-)

**Comment by aislinnpearson** [comment]
Hey @paul121,

I was just having a look at this and it works really well for plant and structure assets, but it doesn't seem to work for land assets (fields/ experiment boundaries). I also wanted to test it for Group assets (but couldn't create the groups - forgot to check this with you last night). 

It also works for plot assets _but_ the plot assets are pretty hard to find. Their naming isn't intuitive ([experiment code]: [plot_number] which is good for computers, but maybe less obvious to people) and you have to know that in order to do the search. It also becomes an issue when you want to search for the quantities associated with a large number of plots, and you have to type them all in. The important thing though is that it works for plots, so I have added this as a nice to have data extraction issue which we can resolve after field net is replaced (#326)

**Comment by paul121** [comment]
> I was just having a look at this and it works really well for plant and structure assets, but it doesn't seem to work for land assets (fields/ experiment boundaries).

Aha, the issue here is that we only add an asset filter for the `log.asset` field, not the `log.location` field. So you can only filter to show quantities relating to the log's target asset, not quantities relating to the log's location. @mstenta what do you think, could we could add a `location` filter to the quantity view as well?

> Their naming isn't intuitive ([experiment code]: [plot_number] which is good for computers, but maybe less obvious to people) and you have to know that in order to do the search. It also becomes an issue when you want to search for the quantities associated with a large number of plots, and you have to type them all in.

Ah yes. I think this is a larger issue that we won't be able to solve in farmOS-core immediately. If the ability to view quantities associated with a plot is important we could add a `Quantities` tab on the `Plots` page, similar to how the `Logs` tab works.

> The important thing though is that it works for plots, so I have added this as a nice to have data extraction issue which we can resolve after field net is replaced

Thanks for opening a new issue. I think it is clear that the existing Quantities page is not sufficient for the proper data extraction you are looking for. I would recommend we create a new workflow for extracting plot quantities :+1:

**Comment by aislinnpearson** [comment]
Sounds good to me. thanks @paul121

**Comment by mstenta** [comment]
> @mstenta what do you think, could we could add a location filter to the quantity view as well?

I suppose so!

I wonder if that would cause any confusion? Do you think someone might look at it and thing "Oh I can filter to quantities that reference and asset in this location?" Rather than understanding that it is ONLY the `location` reference on the log. Maybe that's OK - seems like it would be intuitive that it's just log location... or maybe we could label it "Log location" just to be explicit?

**Comment by aislinnpearson** [comment]
I pictured it more as being able to search any type of asset (including land assets), regardless of what that asset is or if it has a location geometry. I guess it depends how you assign logs in FarmOS... we link our logs (ideally at least) to the land and the plant asset, but other users might do it differently. If I am being honest @mstenta I found it was unintuitive that I couldn't search quantities associated with land assets, as they tend to be one of the main types of asset we use...

**Comment by mstenta** [comment]
@aislinnpearson It *can* search any type of asset... but the filters are tied to a specific field on the logs. So the "Asset" field is tied to the "Assets" field on the log. But as I understand it, that's NOT where we are saving Land assets. We are saving them to the "Locations" field on the log. Both are asset reference fields, but one of them means "this log happened TO this asset" while the other means "this log happened IN this asset". Subtle distinction, but it means if we want to search by both fields we either need two filters in the quantity view, or one combined filter (which would require more development because that doesn't exist right now). Adding a second filter for "Location" is easier.
