### ISSUE TITLE
Create action for bulk assigning the asset's parent

### ISSUE THREAD

**Issue by paul121** [Rothamsted-Ecoinformatics/farm_rothamsted#283]
> BUT maybe we have to accept that, for the initial version, these edge cases would need to be edited manually?

Yep, exactly. Perhaps we could make an action for bulk assigning the asset's parent if that would make it easier.

_Originally posted by @paul121 in https://github.com/Rothamsted-Ecoinformatics/farm_rothamsted/issues/256#issuecomment-1224292971_

**Comment by paul121** [comment]
This may be useful in farmOS more generally. @aislinnpearson seems like this is a lower priority but wanted to open an issue for it anyways.

**Comment by aislinnpearson** [comment]
HI @paul121 

I have labelled it as a must do because I think it will be quite important for some of our experiments and I don't think it's a very difficult thing to code, so the effort to code it is probably equivalent to us having to individually assign the parent locations for a single experiment. But generally I agree it isn't as high priority as some of the other features. Certainly very useful to have though.

**Comment by paul121** [comment]
Hey @mstenta do you think this is something worth adding to farmOS core? It would not be any more work to make this a core feature. My only worry is that we start creating too many bulk actions.

**Comment by mstenta** [comment]
Makes sense to me, but I would echo the same concern. I say we go for it and fix the "too many" as a separate thing.

**Comment by aislinnpearson** [comment]
@paul121 let me know when you have made the update to the core module - I guess if it is added to FarmOS core it won't be included in the next Rothamsted release but I can at least move the issue to that milestone and mark it as done. 

@mstenta if you can then let me know when you next push an update for core I can double check if it is all implemented as we expected. Unless there is some way that I can follow those releases myself? Sorry if that's an obvious question.

**Comment by mstenta** [comment]
Good question @aislinnpearson - not obvious! This hasn't been completed in farmOS core yet, but sounds like it will. New releases of farmOS don't happen on a fixed schedule... generally when there are enough changes to warrant a release. Hard to say when that will be since we just recently released 2.0.0-beta7 (and I still need to deploy that to Farmier-hosted instances). But it's "on the assembly line" so it will happen! :-)

If this is needed more urgently, maybe we can temporarily add it to the Rothamsted module to get it out sooner?

**Comment by mstenta** [comment]
> New releases of farmOS don't happen on a fixed schedule... generally when there are enough changes to warrant a release. 

Just want to add: since we're still in "beta" (eg: `2.0.0-beta7`) right now the releases are a bit more spaced out, but once we're in "stable" we'll be using semantic versioning (eg: `2.0.1`) so so the hope is we'll get into a pattern of putting out more frequent minor and patch releases, so things will move more speedily (that's the hope!)

**Comment by paul121** [comment]
I've added this within the rothamsted repo for now. I'll create a PR to farmOS soon and create a new issue here that we can use to track once the feature is in farmOS core and remove/migrate to the core version when ready.

**Comment by paul121** [comment]
Keeping this in the 2.8 milestone so we have record of when this was added to the rothamsted code
