### ISSUE TITLE
Include plant assets that have been moved to sub-locations in quick form asset field

### ISSUE THREAD

**Issue by paul121** [Rothamsted-Ecoinformatics/farm_rothamsted#293]
From https://github.com/Rothamsted-Ecoinformatics/farm_rothamsted/issues/286#issuecomment-1245948550 we identified that we need to include all plant assets that have been moved to sub-locations of a location hierarchy in the quick form asset field. This is largely for legacy use-cases and could potentially be removed in the future.

I did not include this when first working on this in https://github.com/Rothamsted-Ecoinformatics/farm_rothamsted/issues/260 because I worried that this could potentially load a large number of plant assets if a hierarchy was particularly large. But I don't think we'll have a way around this as it is a requirement for the legacy experiment data where each plot had a land asset and a plant asset. This could potentially be removed in the future.

Things to do:

- [x] Alter this query to load assets moved to sub-locations of the selected location: https://github.com/Rothamsted-Ecoinformatics/farm_rothamsted/blob/339a69515a2cde4cbb77825bbe8dbc61e8902953/modules/farm_rothamsted_quick/src/Plugin/QuickForm/QuickExperimentFormBase.php#L275-L279

**Comment by aislinnpearson** [comment]
Thanks for doing this @paul121 - and for making the two new issues. That makes sense. Hopefully all these related issues mean we now have the architecture we want in the quick form.

A couple of things:

1. I created a 'for review' column on the live and Phase 2 project boards, and moved this issue there so we don't loose track of it.
2. I tried testing this in the 2.7.0 platformish site but it wasn't selecting the land assets. I thought this might be because there were no plant assets associated with the location, but even in the 'Create commercial asset' quick form the locations don't seem to be selecting (or filling in the name when I enter them manually). Not a big deal, but I've realised it's actually really nice to have these historic versions of the website to refer to when I want to see how something _was_ before specifying something new (something to chat about on the call tonight).

![image](https://user-images.githubusercontent.com/16349781/191222908-a3f4b45c-2ead-41e2-a840-f13d5d3f4bcf.png)
