### ISSUE TITLE
Experiment Module: Add separate views of experiment logs in secondary tabs

### ISSUE THREAD

**Issue by aislinnpearson** [Rothamsted-Ecoinformatics/farm_rothamsted#303]
I think this might be more of a clarification than a question:

I was chatting to the farm team about how we visualise logs associated with experiments. My feeling is:

- **Plots** only show logs assigned to that plot (i.e. plot treatments applied)
- **Experiment assets** only show logs assigned to that asset (i.e. basal treatments applied)
- **Experiment Plans** show all logs associated with an experiment (plots and plans)

This way you would be able to see:

1. A list of all basal treatments
2. A list of treatments applied to a specific plot
3. A list of all plot treatments and basal treatments

The only down side to this is that you'd never be able to:

1. click on a plot and see only the records associated with that plot
2. see only a list of plot applications

One for discussion I think

**Comment by paul121** [comment]
We already have a "Logs" tab for experiment plans. Add secondary tabs for: All, Experiment boundary, and Plots to only show relevant logs.

**Comment by paul121** [comment]
I've implemented this. Right now we don't have a great way to identify the "Experiment boundary" asset itself since this is stored in the `plan.asset` field...  so I've called this tab "Experiment asset" so it will show logs relating to _any experiment assets._ 

Typically I wouldn't think there to be too many assets in this `plan.asset` field. If & when there are more than the experiment boundary then I would assume they are all of interest, so it would be nice to include their logs on this page as well. Perhaps an additional step we could take to make this clear is list when "Experiment assets" we're talking about at the top of this page eg: "Viewing logs referencing assets associated with this experiment: Experiment boundary 1, experiment landmark 2, experiment monitoring area 3".

I think this is the best we can do for now @aislinnpearson but I'm curious what you think, if this will be a "feature" or an "issue" in the long run... :-)

![Screenshot from 2022-11-14 14-48-43](https://user-images.githubusercontent.com/3116995/201784298-957c40e7-7bd2-4fff-acbd-2c697595ece7.png)

**Comment by aislinnpearson** [comment]
Hey @paul121 

Thanks for doing this. TO answer your question

> Typically I wouldn't think there to be too many assets in this plan.asset field. If & when there are more than the experiment boundary then I would assume they are all of interest, so it would be nice to include their logs on this page as well. Perhaps an additional step we could take to make this clear is list when "Experiment assets" we're talking about at the top of this page eg: "Viewing logs referencing assets associated with this experiment: Experiment boundary 1, experiment landmark 2, experiment monitoring area 3".

I actually did the first one of these yesterday for 2023/R/WW/2318: a GM experiment which has an experiment boundary _and_ a pollen barrier beyond that (see https://rothamstedfarm.farmos.net/plan/26). An you are right, we would want to see logs for both boundaries. A nice feature of what you have show above is that I assume we could also filter to only see the logs of one based on the name of the asset?

Still, I agree with you. It would be useful to see what assets are being referenced. But are you thinking the boundaries should be their own asset type as well? Another to chat about this evening perhaps...

**Comment by aislinnpearson** [comment]
Notes from the meeting on Tuesday:
- Change 'Experiment assets' to 'Land Assets' for clarity. In future might also want a tab for 'sensor assets'
- Include helper text above the filter so users know that they are searching land assets linked to the experiment

**Comment by paul121** [comment]
Rename tabs to "Plot assets" and "Other assets"

**Comment by paul121** [comment]
I would also like to add a bullet list of what the "Other assets" are (those linked to the `plan.asset` field)

**Comment by paul121** [comment]
![Screenshot from 2022-11-18 15-01-41](https://user-images.githubusercontent.com/3116995/202817279-2fd6ec79-b6f3-427d-80ba-d83d542f6d1d.png)

done!

**Comment by aislinnpearson** [comment]
Looks really good @Paul :)

**Comment by aislinnpearson** [comment]
Working on the Harpenden module as well:

![image](https://user-images.githubusercontent.com/16349781/204573542-9dd3dfd9-416a-4df1-8d21-313c4d3b02a0.png)
