### ISSUE TITLE
Enable comments for proposal

### ISSUE THREAD

**Issue by aislinnpearson** [Rothamsted-Ecoinformatics/farm_rothamsted#325]
When the experiments are going through planning, management and archive, there is often a lot of discussion around treatments, plans and data. Ideally this discussion would be associated with the experiment plan so people can refer back to it and use it as a single reference point through the growing season.

According to @paul121 Drupal modules for this do exist

**Comment by aislinnpearson** [comment]
Next step: to do a bit of research into what is and isn't feasible

**Comment by mstenta** [comment]
I opened this core farmOS issue: https://www.drupal.org/project/farm/issues/3352183

I think it would be worth looking into adding a new core farmOS Comment module that adds comments to assets and logs, and also provides standard config for other modules to use as well, eg so that the Rothamsted module can also enable them on our custom entity types.

Or, after learning more, we may decide that a core module doesn't make sense (yet), and just implement it in the Rothamsted module to start.

**Comment by aislinnpearson** [comment]
Hi @mstenta ,

> I opened this core farmOS issue

As always our preference is for features that improve FarmOS for the whole community, if that seems sensible. Not least because I also really like the ability to comment on assets, although it does slightly make me wonder if the comments would end up replacing the observation logs. I personally still see a need for such logs in our implementation for recording data collection activities (e.g. land surveys), monitoring GM trials and experiment deviations. Although if that doesn't seem sensible, we are also happy to act as a test case. It definitely makes more sense for us to be commenting in FarmOS rather than in different software.

I've started marking these issues with the 'FarmOS core' label so we can report on them to our funders if we are ever asked.

**Comment by paul121** [comment]
@mstenta started this PR investigating comments in farmOS core. This core module could also support comments for Rothamsted entities. https://github.com/farmOS/farmOS/pull/668

There is a bit of a larger question of "what does a comment mean on an asset or log?" This isn't a big deal for the discussion module because the use-case for comments on plans & research entities seems more clear but I just want to note it here. Also worth noting @aislinnpearson that enabling comments for assets or logs is a separate decision, and could even be different on each farmOS instance:
- Comments could get confused with "Notes" for both assets & logs, except that comments have better granularity of author & timestamp.
- Also for assets there is a concern that comments could be used for "Observations" about an asset, when instead observations should probably be recorded as "Observation logs"

@aislinnpearson I should also explain the "comment settings" option. When comments are enabled for an entity type (eg: assets) each asset will have a "Comment settings" option with 3 options: Open (can post comments, show all), Closed (cannot post new comments, but show existing) or Hidden (cannot post, no comments are shown). We can set the default value for this, which basically determines if "Add new comment" would be shown by default. If not, then comments must fist be enabled (set to "Open") before users can post comments. This is also a consideration for assets + logs above ^

![Screenshot from 2023-04-14 14-03-25](https://user-images.githubusercontent.com/3116995/232155351-fb493818-e068-4db2-a69f-b94855d023bf.png)

@aislinnpearson here is a screenshot of Drupal comments added onto the `Proposal` entity. It isn't super pretty - but just want to show what it looks like. Here are some questions/things to think about:

- Which entities need comments? Above you mentioned experiment plans, but now we also have the research entity types. My assumption is it would be useful on proposals, but maybe experiments + designs as well?
- Where should existing comments be displayed:
  - On the "View" tab?
  - And/or on a separate "Comments" or "Discussions" tab?
- Similarly, where should the "Add new comment" form be displayed?
- Permissions:
  - Who can create comments?
  - Who can view comments?
- Default comments to "open" or "hidden" ?

![Screenshot from 2023-04-14 13-47-30](https://user-images.githubusercontent.com/3116995/232155505-b1c02a5f-4f4b-4409-9291-a76c4a458038.png)

**Comment by aislinnpearson** [comment]
Hi @mstenta, @paul121 

Following the discussion with @paul121 on Friday, I'd really appreciate it if this comments module could please be switched on for Rothamsted before the 09 May so we can start using it in the planning process.

Speaking to @paul121, we realise this probably means switching the discussion module on in the Rothamsted instance before it goes live in core, and I am not sure what the implications of that are? Maybe one to discuss this evening.

To also answer some of @paul121's questions above:

 > @aislinnpearson I should also explain the "comment settings" option. When comments are enabled for an entity type (eg: assets) each asset will have a "Comment settings" option with 3 options: Open (can post comments, show all), Closed (cannot post new comments, but show existing) or Hidden (cannot post, no comments are shown). We can set the default value for this, which basically determines if "Add new comment" would be shown by default. If not, then comments must fist be enabled (set to "Open") before users can post comments. This is also a consideration for assets + logs above ^

I think I would choose to have them open so that 'add new comment' is shown by default, but limit the permissions for who can post to people associated with the experiment (everyone can view comments). I think this is in keeping with the 'open research' ethics. We may want to come up with privacy options for some of our commercial trials _but_ that would probably mean hiding more details than just the comments, and the comments would remain 'open' for anyone who could see the details. This needs some thought though, as I'd think the farm management data is still open (it's just the treatments and measurement data that is confidential)

> @aislinnpearson here is a screenshot of Drupal comments added onto the Proposal entity. It isn't super pretty - but just want to show what it looks like. 

It looks pretty good to me - I am more than happy with this to start with

> Which entities need comments? Above you mentioned experiment plans, but now we also have the research entity types. My assumption is it would be useful on proposals, but maybe experiments + designs as well?

From our internal perspective, we are in the proposal phase between the 09 May and the 28 June. During this period scientists are encouraged to submit proposals for review and acceptance so the discussion module would be really useful. From the 28 June the experiment planning starts on the approved proposals (when we will fill in the experiment, design and plan entities). So we could just enable the discussion module on the proposal entity for now, and I'll create a sperate issue for turning it on for the experiment/ design/ plan entities - or we could put it on all four entites from the start. I'm open to suggestions here from you and @mstenta 

> Where should existing comments be displayed:
> On the "View" tab?
> And/or on a separate "Comments" or "Discussions" tab?

I'd say on the view tab so the user can read what is written and comment underneath? This isn't as tidy, but probably easier to use?

> Similarly, where should the "Add new comment" form be displayed?

At the bottom of the view page would be my first instinct.

> Permissions:
> Who can create comments?

Proposal: anyone who is an experiment admin or who is listed as an _active_ contact on the proposal (archived users shouldn't be commenting)
Experiment, Design and Plan: anyone who is an experiment admin, or who is listed as an _active_ researcher on the experiment (archived users shouldn't be commenting)

> Who can view comments?

Anyone who is an experiment viewer or sponsor (although these permissions need reviewing)

Default comments to "open" or "hidden" ?

Open

Let me know if that all makes sense, and if it's possible to get the module up by the 9th.

Thank you so much both,

Aislinn

**Comment by mstenta** [comment]
> we realise this probably means switching the discussion module on in the Rothamsted instance before it goes live in core, and I am not sure what the implications of that are?

I spoke with @paul121 about this, and it should be easy to do this. The work we did to enable comments in farmOS core ultimately taught us what was needed here. And now Rothamsted can beat farmOS core across the finish line for its own needs. Core can take its time to get further feedback from the community on theming, default settings, etc. :-)

**Comment by aislinnpearson** [comment]
Okay, great. Thanks so much @mstenta

And we are only implementing them in the research modules so hopefully we can benefit from whatever the outcome is from the core discussions to. :)

**Comment by paul121** [comment]
Follow up issue for email notifications #436
