### ISSUE TITLE
Experiment Module: Create a new user profile specifically for Experiment Administrators

### ISSUE THREAD

**Issue by aislinnpearson** [Rothamsted-Ecoinformatics/farm_rothamsted#341]
See #76 for background. This still needs some thought/ discussion but initial suggestions on permissions are:

**Experiment Administrator User Profile Permissions:**

**Can view all logs, assets and plans (the equivalent of a 'Viewer' which is their current level of permission) with the following additions:**

1. Create new experiment plans
2. Add new logs and assets to all experiment plans
3. Edit logs and child assets (e.g. plots and experiment boundaries) associated with all experiment plans 
4. Delete logs and child assets (e.g. plots and experiment boundaries) associated with all experiment plans 
5. Archive logs and child assets (e.g. plots and experiment boundaries) associated with all experiment plans 
6. Delete experiment plans

**Comment by paul121** [comment]
I'm just now noticing this issue. Most of this is already done.. if someone has the `experiment admin` role *and* `manager` or `worker` then they can do all of the above. `experiment admin` by itself does not do much. Instead of making this role do everything I think it should be combined with existing/additional roles to add the desired capability

Unless @aislinnpearson there is a clear use-case for making the `experiment admin` role itself provide everything. Let me try and explain how it currently works:

- I added some logic that only lets users `update` or `delete` experiment plans and the plan's plot assets IF they are listed as a contact OR if they are an experiment admin. _All other permissions/logic behave normally_
- Right now if a user can create/update logs, they can create/update logs referencing any asset. If they can create/update assets, they can create/update any asset UNLESS if it is a plot asset on an experiment they don't have access to. Currently these permissions are available via `manager` and `worker` roles.

Maybe we need to add additional restrictions for the following:
- Restrict log create/update to consider if the log references any `plot` assets
- Restrict updating of "child assets" and "experiment boundaries" (I'm weary of child assets, since these could be associated with multiple experiments!)

Consider this theoretical use-case: `sprayer` role. This user could only create/edit `input` logs. If given an `experiment admin` role then they also create/edit `input` logs on any experiment. Without `sprayer` role they cannot create logs.

**Comment by aislinnpearson** [comment]
Hi @paul121,

> Instead of making this role do everything I think it should be combined with existing/additional roles to add the desired capability

I agree. I hadn't thought of it this way, but I think that is an ideal first version (we can add permissions later and as it becomes obvious they are necessary). 

> I'm just now noticing this issue. Most of this is already done..

In fact, I think there was some confusion here because I thought the experiment admin role you have already created was for this issue, and this one just needed closing. It was on my list of things to do :)

Still, I'm glad we are having this conversation because I do get a bit confused about who can do what. I think it's an important thing to document and include in the user guides. So just to talk it through so I can make sure I understand:

> I added some logic that only lets users update or delete experiment plans and the plan's plot assets IF they are listed as a contact OR if they are an experiment admin. All other permissions/logic behave normally

So you can **only** edit plans if you are (a) an experiment admin (in which case you can edit all experiment plans) or (b) a sponsor (in which case you can only edit plans where you are listed). Sponsors can **_only_** add observation logs currently.

> Right now if a user can create/update logs, they can create/update logs referencing any asset. If they can create/update assets, they can create/update any asset UNLESS if it is a plot asset on an experiment they don't have access to. Currently these permissions are available via manager and worker roles.

So anyone listed as a worker or a manager can create logs accessing for **any** asset **except** plots. I can see that getting a bit complicated as we have members of the farm team who aren't experiment admins, but do sometimes (not often) do trials work. 

> Restrict log create/update to consider if the log references any plot assets

My feeling is that if you are a worker, it's okay to add logs to any asset including plots but what I am not sure about is if that makes things more complicated for you and how that affected the above suggestion?

> Restrict updating of "child assets" and "experiment boundaries" (I'm weary of child assets, since these could be associated with multiple experiments!)

I hadn't thought about child assets and experiment boundaries if I am being honest. The other type of asset to add here is sensor assets associated with the plan. I'd also wonder how this affects the ability to edit and add columns, and add or remove plots during the planning phase. Normally this would have to be done with permission from the farm team... I think this is something we should talk through before making any decisions.

Sorry for all the complexity Paul - this is turning out to be more complicated than I thought. Better to go slow and get it righ though, or we may end up with some fairly serious bugs on our hands. Especially with the number of plot child assets we will be storing, as you pointed out.

**Comment by paul121** [comment]
We spoke about this more today - indeed this issue was already completed with #76 

There could be additional complexities we add over time but for now this is sufficient.
