### ISSUE TITLE
Experiment Module: 'Researchers' entity

### ISSUE THREAD

**Issue by aislinnpearson** [Rothamsted-Ecoinformatics/farm_rothamsted#354]
Create an entity for collecting metadata about researchers. See https://github.com/Rothamsted-Ecoinformatics/farm_rothamsted/issues/298#issuecomment-1411784802

**Comment by aislinnpearson** [comment]
Hey @paul121,

Tested this and it works well. Thank you!

**Comment by aislinnpearson** [comment]
Hi @paul121,

I was just triple checking this and (as we were talking about minor edits) noticed that the email address is lacking a description (my fault for not including it on the original spreadsheet). I've also added/ edited the minimum form validation logic.

I'll upload the full spreadsheet a bit later but here is a screenshot in the mean time:

![image](https://user-images.githubusercontent.com/16349781/221570421-3d961a80-b22c-4633-bc37-e98d2587b91d.png)

**Comment by paul121** [comment]
Okay, I added the email description and made both email and role required fields :+1: 

Also @aislinnpearson I see you highlighted the data field IDs here. I currently do not have a `researcher_` prefix on these fields or any of the other custom entity types. The reason is the entity type is know through the context of the API, and saving it in the field ID would be redundant. We also have a limited length for field IDs so its good to keep them short when possible. Otherwise all of these are the same - with the exception of `farmos_id`, `farmos_name`, and `farmos_user_profile` - these are `id`, `name`, and `farm_user` respectively. Let me know if that makes sense or if you have any issues!

**Comment by aislinnpearson** [comment]
Thank you so much for this @paul121 

> Also @aislinnpearson I see you highlighted the data field IDs here. I currently do not have a researcher_ prefix on these fields or any of the other custom entity types. 

That's fine - in fact, it's kind of a relief and I was worried I'd change them and you'd end up having to change a lot of your code. In that case I think I will  replace them with the data field names you are using. I just wasn't sure so I wanted to highlight the fact that they had changed. I'll mark this for documentation for that reason.

otherwise I have checked all the changes and they look good to me! I'll close this issue.

**Comment by paul121** [comment]
@aislinnpearson all entities are defined in a file at the following path within each module: `src/Entity/{EntityName.php}`. In this file there is a function called `baseFieldDefinitions()` which returns an array of the field definitions, each key in the array being the field ID.

Researcher fields are defined here: https://github.com/Rothamsted-Ecoinformatics/farm_rothamsted/blob/87b8c8309a4ad76bb73ae8856393c3dfa73267c9/modules/farm_rothamsted_researcher/src/Entity/RothamstedResearcher.php#L156-L354

And here are the other program, experiment and design entities (click on individual files to see the fields): https://github.com/Rothamsted-Ecoinformatics/farm_rothamsted/tree/2.x-2.10/modules/farm_rothamsted_experiment_research/src/Entity
