### ISSUE TITLE
Experiment module: Add proposal entity

### ISSUE THREAD

**Issue by paul121** [Rothamsted-Ecoinformatics/farm_rothamsted#380]

**Comment by aislinnpearson** [comment]
Hey @paul121 

Thank you so much for doing this. I have a list of minor edits (which also includes Andrew Riche's suggestions):

**Description Tab:** 
- **'Related Experiment(s)';** 
-- move to Status tab 
-- edit the description to say "The experiment(s) relating to this proposal. If this is the second or subsequent year of an experiment that has already been added to FarmOS, please select it here before submitting the proposal. If this is the first year of the experiment, leave this blank and add it _after_ the proposal is approved."
- **'Related Design(s)':**
-- move to Status tab 
-- edit the description to say "The experiment design relating to this proposal. If this design has already been added to FarmOS, please select it here before submitting the proposal. If this is the first year of the experiment, or if you wish to change the design from previous years, a new design will have to added _after_ the proposal is approved."
- **'Proposed Amendments:**
-- Move 'Proposed Amendments' to Status Tab
-- Please make this an 'add multiple' question so that multiple proposed amendments can be added if necessary.
--  Please change the description to "Amendments required before the proposal can be approved".
- **Experiment Category:"** Add a data field for "Experiment Category" (this is the same as on the 'Category' on the experiments tab)
- **Name:** edit description to say 'The name of the proposal. If the experiment is already in FarmOS, please be consistent in how you name the proposal each year. For example "WGIN Diversity (2023)" should "WGIN Diversity (2024)" in the following cropping year.'
- **Please can we have 'Add another item' for:** 
-- Research Questions (to separate the questions if there are more than one) 
--Hypothesis (again, to separate them out if there is more than one)

**Design Tab**
- **Plot length/ width:**  Plot length and plot width data fields should be decimals (my mistake, sorry)
- **'Field Layout:** 
-- rename this as 'In-Field Layout'
-- change the description to "Please describe how you would propose to lay the experiment out in the field (guard rows, row spacing, number of plots per row, etc) and any limitations that would affect where the experiment can be situated."
- **Measurements:** please can we 
-- make this 'add multiple' so there is one row for each type of measurement, and;
-- edit the description so it reads "Describe the measurements you propose to take, approximate dates and who is responsible for taking the measurements. This should include measurements to be taken by the farm (yields, etc), measurements to be taken by the Sponsor, and measurements which will be taken by external consultants." 
- **Experiment management:** Please move the 'Experiment Management" data field to the Management tab (see below)
- **Division of Labour:** This can be deleted (see Management tab below)

**Restrictions Tab:**
- Please add a new yes/no data field for "crop management restrictions".
-- Description: "Are there any restrictions that affect how the crop(s) in the experiment will be managed (cultivations, pesticide applications, etc?)
-- if 'yes' please make a required long text field for "Description of Crop Management Restrictions", with the description "Please describe the crop management restrictions. Note: All aspects of crop management will need to be discussed in detail with the trials team once the proposal has been approved."
- Please add a long text add multiple data field for "Other Restrictions".
-- Description: "If there are any other restrictions not covered above, please add them below".

**Farm Management Tab:**
- Please can we create a new tab for farm management
- For each of the below, please can we create a 'select multiple' field with the options "Farm", "Sponsor" and "Other"
-- **Seed Supply:** with description "Who will supply the seed for this experiment. Please select multiple if this is a shared responsibility."
-- **Seed Treatment:** with description "If the seed needs to be treated, please state who is responsible for this. Please select multiple if this is a shared responsibility." (NB: this list needs to have the additional option of "Supplier").
-- **Pesticide Applications:** with description "Who is responsible for the pesticide applications? Please select multiple if this is a shared responsibility."
-- **Nutrition Applications:**  with description "Who is responsible for the nutrient applications? Please select multiple if this is a shared responsibility."
-- **Harvest:** with description "Who is responsible for harvesting the experiment? Please select multiple if this is a shared responsibility."

**Comment by paul121** [comment]
I believe I've made all of these changes
