### ISSUE TITLE
Cleanup experiment plan fields

### ISSUE THREAD

**Issue by paul121** [Rothamsted-Ecoinformatics/farm_rothamsted#385]
2.10 is adding various fields to experiment plans. Some of these fields are now duplicated if they are included on the new experiment or design entities. After 2.10 is out we can do a migration/cleanup of these old fields on the plan entity.

From #384 
> on the Description tab please can we remove the 'project code' data field (this is now on the Program entity) and the Objective(s) data field (this is now on the Experiment entity)
Please can we rename 'Drilling year' as 'Planting year' (that way the terminology also covers crops such as willow which are transplanted rather than drilled).

Updated list of changes:
- [ ] Rename 'Experiment code' as 'Study Period ID' with the description "The unique identifier for the study, for example 2020/R/CS/790."
- [ ] Rename 'Drilling Year' as 'Planting Year', and change the description to "The planting year for the study"
- [x] Remove the project code field (this in now on the Research Program)
- [x] Remove start date and end date (the planting and harvest dates are adequate)
- [x] Remove Experiment Category (this is now on the experiment entity)
- [x] Remove 'Objective' (this is now on the design entity)
- [x] Remove 'Amendments' (these should either be captured in a new design or as deviations to the plan)
- [x] Move Flags to the Experiment Status Tab
- [x] Move Status to the Experiment Status Tab
- [ ] **Remove the 'People' tab (this has been replaced by the 'Researchers' on the experiment entity** _How does this affect permissions?_
- [ ] **Change the 'Experiment Plan' and 'Experiment Files' to links.** Can we name links? _Can we name links and use these as the name?_

**Comment by aislinnpearson** [comment]
HI @Paul,

I just double checked this and you've done everything perfectly, but I'm questioning my own logic. 

**Design:**
- Ideally we should put blocking structure before statistical design in the columns and search terms just because the blocking structure determines the design (and it would be consistent with what is on the form).
- I wonder if we should put all three elements in (i.e. add `Additional Blocking Constraints`)?

**Proposals:**
- Can we move the status notes so they come after the status (to be consistent with the experiment, designs and plans)

**Plans:**
- To make additional space, we could remove experiment category from the columns (just keep it as a searchable term)
- For the life of me, I don't know why I asked you to add status notes to the list of searchable terms. Can we remove it?

This is just a list of the things that occurred to me when checking the issue in the dev version. We can do the actual work in 2.11.x, which I think I would prefer to delaying 2.10.x

**Comment by aislinnpearson** [comment]
Aislinn to create basic implementation and request scientists/ statisticians to add details (possibly as a training exercise)

**Comment by paul121** [comment]
Most of this is done, moving remaining items to a follow up issue: #437
