### ISSUE TITLE
Proposal Entity: Add validation criteria based on proposal status

### ISSUE THREAD

**Issue by aislinnpearson** [Rothamsted-Ecoinformatics/farm_rothamsted#434]
Please can we edit the proposal entity so it's minimum validation criteria enables draft submissions. Specifically please can we:

1. Add 'Draft' to the list of proposal statuses
2. Edit the required fields so that only the following are required:
- Related program
- Proposal name
- Proposal contact
- Proposal status

**Comment by paul121** [comment]
This is done, and I've done this in a way (using a field item "constraint validator") that should be easy to replicate on other entities.

One thing to note is that I have left the Proposal "Restriction" fields all as required items... this is because there is not an easy way to make them conditionally required based on status while keeping the UI that enforces a Yes/No is selected. When the field is optional an additional "N/A" option appears and is difficult behavior to change, although we could investigate this in a follow up.
