### ISSUE TITLE
Experiment Plan: Remove the 'People' tab

### ISSUE THREAD

**Issue by aislinnpearson** [Rothamsted-Ecoinformatics/farm_rothamsted#459]
Please can we remove the 'People' tab (this has been replaced by the 'Researchers' on the experiment entity).

Before doing this, we need to confirm how this affects the permissions

**Comment by paul121** [comment]
> Before doing this, we need to confirm how this affects the permissions

I've made these changes. The permissions have been updated so that they do not use the `plan.contact` user reference, but instead the `experiment.researcher` reference & user reference to determine who can edit/delete an experiment plan.

In this process I've discovered there is a slight issue with these permissions - it is possible for a user to create a new experiment plan that is associated with an experiment/design that the user themselves is not a part of. However, once created, this user would not have permission to edit/delete the experiment plan, but an experiment admin could. This is an existing issue that I think would be best fixed when re-thinking the process of creating experiment plans where we could include this additional logic: eg auto-copy data from the experiment/design to the plan, ensure the user is associated with the experiment/design, etc. (Maybe via a quick form?) Also perhaps related to #377
