### ISSUE TITLE
Experiment Module: Email alerts for management records

### ISSUE THREAD

**Issue by aislinnpearson** [Rothamsted-Ecoinformatics/farm_rothamsted#469]
Please can we change the email alert settings so that the Researchers associated with an Experiment get an alert every time a management record is submitted for a plan associated with that experiment.

**Comment by paul121** [comment]
To clarify the logic here because logs are not directly associated with the `plan`, but rather the 1) experiment boundary or 2) plot assets (which are children of the experiment boundary):

- When a management record (any log) is submitted (when the log is created: do we care about pending/done status?)
- Check if the log references any asset that is either:
  - 1) The plan's experiment boundary
  - 2) A child of the experiment boundary (includes plots or other sub-location assets)
- Send email to researchers associated with the experiment (using relationship: experiment -> design -> experiment plan)
  - Only send to researchers that are "active"?
  - Only send email if the experiment status != active/terminated? yes no?

**Comment by paul121** [comment]
I've added a simple pass at this... I imagine we might want to refine these emails in the future but this should be a good start to get things going.
