### ISSUE TITLE
Experiment Plans: Add validation for sequential column level level_id

### ISSUE THREAD

**Issue by aislinnpearson** [Rothamsted-Ecoinformatics/farm_rothamsted#483]
For some of the experiments (not all) the scientists have specific varieties (or other details) for the guard plots, which don't always import.
Ideally the default would be that if these are provided, they should be imported (although currently I think it is na for all variables)

example for 2023/R/CM/2337 below:

file upload:

![image](https://github.com/Rothamsted-Ecoinformatics/farm_rothamsted/assets/16349781/648080ae-d237-43e6-a708-8d246a3be58e)

FarmOS plots:

![image](https://github.com/Rothamsted-Ecoinformatics/farm_rothamsted/assets/16349781/2ef938e8-b143-4a81-878b-4aaf3f6ea40f)

**Comment by paul121** [comment]
Interesting... the guard plots should allow any variable to be assigned to them, in this case the `line`. I went to this same experiment plan and noticed that some treated plots do not have the `line` variable either though. I can also filter by a specific `line` and it seems to work, however the `line` is not displayed: https://rothamstedfarm.farmos.net/plan/60/plots?name=&status=active&EFO_0005136%5B%5D=18&items_per_page=100

So I think this might actually be a different bug where some of the variable levels do not have a label being rendered. Will continue looking...

**Comment by paul121** [comment]
Eek! Filtering by other `line` filter options returns plots with a `line` that wasn't specified... this led me to find the real issue: (not including screenshots of the filtering for data sensitivity)

The `level_id` for the column levels in this specific experiment are not all sequential within their respective column: eg: 1,8,9.7,4 should be 1,2,3,4...

![Screenshot from 2023-06-12 09-02-40](https://github.com/Rothamsted-Ecoinformatics/farm_rothamsted/assets/3116995/8e4fdc29-90cc-4fc2-a355-819785c4782f)

@aislinnpearson if you re-upload the column levels for this experiment then I think this will work as expected: https://rothamstedfarm.farmos.net/plan/60/variables

I thought we were validating this in the upload form but turns out I have a remaining @todo for this:

https://github.com/Rothamsted-Ecoinformatics/farm_rothamsted/blob/56868dbd6cab487f6fabd7ba638a6ccdbf313663/modules/farm_rothamsted_experiment/src/Form/ExperimentVariableForm.php#L294-L300

**Comment by paul121** [comment]
@aislinnpearson I'm making the assumption that we do want sequential column level IDs and that is is not a feature to have non-sequential level_ids... IMO it is best to use sequential here. If we need a place for a non-sequential identifier (maybe internal to rothamsted or a specific program/experiment) then we could add additional column metadata for that.

**Comment by aislinnpearson** [comment]
Hi @paul121,

So this is my mistake again. I corrected the upload so the level ids for line were sequential, and now the variety of the guard plots displays: https://rothamstedfarm.farmos.net/plan/60/plots

![image](https://github.com/Rothamsted-Ecoinformatics/farm_rothamsted/assets/16349781/3cbf6a10-b9e5-443f-b622-2381a7c19e76)

So I guess it is worth asking if we need to make the system fool proof enough to withstand people like me!

As an aside for issue #484 I deleted the previous upload files in this instance, but in future I wonder if we should follow a process more similar to that described for assets and logs in #474
