### ISSUE TITLE
Proposal entity: Add drill spacing

### ISSUE THREAD

**Issue by aislinnpearson** [Rothamsted-Ecoinformatics/farm_rothamsted#510]
Please can we add an 'add multiple' text box to the management (planting) tab on the ~proposal~ design entity:

Field name: Drill spacing
Type: long text (add multiple)
Description: Request specific drill spacing.

**Comment by paul121** [comment]
@aislinnpearson for both this and #511 I have a question. The design entities have a Management -> Planting/Nutrition/etc sub-tabs, but the proposals do not. I guess I just want to confirm that you still want to add this to the standard "Farm Management" tab for proposals?

I'm also curious how many more of these management items we might be adding in the future... totally happy to add these for now but eventually I wonder if it would be better to re-architect how these management items work so that is is easier to add new ones on the fly. This may also help in being able to copy proposal metadata to a design.

**Comment by aislinnpearson** [comment]
Hey @paul121 - thank you for catching this. I do mean the design entity and not the proposal entity. I think I was on autopilot and typed the wrong thing in. Thanks for pointing it out/ double checking!

**Comment by aislinnpearson** [comment]
Mis-specified. Needed in Design entity only. Can be closed.
