### ISSUE TITLE
Rothamsted Module: Comment on logs 

### ISSUE THREAD

**Issue by aislinnpearson** [Rothamsted-Ecoinformatics/farm_rothamsted#574]
Following on from issue #524 we decided _not_ to let research leads or editors make changes to logs that are associated with their experiments (with the exception of observation logs where they can edit their own). The reason for this is that the drilling, activity, input and harvest logs sometimes cover multiple experiments to they would be editing logs associated with other people's trials instead of their own.

Instead we would like to look into extending the commenting functionality so that researchers can comment on logs, mark them as 'needs review' and possibly 'at' people so that they get an alert that there is a comment for them to reply to.

This issue originally also included commenting on assets and other experiment entities, but that has been replaced by the below issues:
- #599 
- #600
- #601
- #602 
- #603 
- #604

**Comment by paul121** [comment]
It makes a lot of sense to allow commenting on, but not editing log/assets/research entities for these use-cases!

We started working on a core module for log/asset comments but just didn't turn it on. It's safe to say we could use/adapt that and at least know we have a path forward.

I would like to learn more about the needs review use-case here. We could potentially allow some comments to add a "Needs review" flag to the logs/assets? Then owner of the logs/assets (those that can edit/are responsible) could have a page that shows all of these that "Need review"?

I'm not sure how difficult "at/mentioning" people could be... it is quite possible a Drupal solution already exists. But because comments are entities w/ bundle fields themselves, I suppose we could add a `comment.user_mention` user-reference field :thinking: This wouldn't be the UI that many are accustomed to where you can mention inline with your text - instead you would write a comment and then select which users to "mention", but this could be quite functional.

**Comment by aislinnpearson** [comment]
Discussing this on the 24/11/2023 we agreed that we would start with the commenting functionality but the option to add a 'Needs review' flag can come later (as would need to be hard coded in, especially for users who don't have editing permissions for that entity/ asset/log).

Similarly with the 'at' functionality can come later once issues such as #506 have been addressed

@paul121 to re-evaluate if should be added to FarmOS core

**Comment by aislinnpearson** [comment]
Discussing this with Mike and Paul, this should be released as part of FarmOS core in February/ March so agreed we will wait until then.

**Comment by paul121** [comment]
Somewhat a question for all of these new comments, but what permissions would we like to restrict this to? Can any user comment on an entity they have access to view?

And what about for reviewing + flagging logs, does this only require the same permission?

**Comment by paul121** [comment]
This should all be complete now.
