### ISSUE TITLE
Bug: error uploading plot geometry

### ISSUE THREAD

**Issue by aislinnpearson** [Rothamsted-Ecoinformatics/farm_rothamsted#584]
Hi @paul121 

We are having a problem uploading a GeoJSON of plots to the North Wyke instance, getting the below error:

![image](https://github.com/Rothamsted-Ecoinformatics/farm_rothamsted/assets/16349781/f93372cc-ef57-47df-b882-6ef9ea83202a)
 
when we try to upload the GeoJSON file (sent separately by e-mail) to this plan: [https://northwyke.farmos.net/plan/8/plots](https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fnorthwyke.farmos.net%2Fplan%2F8%2Fplots&data=05%7C01%7Caislinn.pearson%40rothamsted.ac.uk%7Ce11a9854eb4e47afb71f08dbec32e078%7Cb688362589414342b0e37b8cc8392f64%7C0%7C0%7C638363475486265013%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=s%2BJAFv%2FZ%2BfYcMqBqv9TGn5cjmZtTEk0KuQ4t%2B3hWvGw%3D&reserved=0).

I think the function is working fine at Harpenden, so I don't know if it's a problem with the file or the site.

**Comment by paul121** [comment]
@mstenta when you have a chance, could you check error logs for this?

**Comment by mstenta** [comment]
Yes I found the error:

`SQLSTATE[22003]: Numeric value out of range: 7 ERROR: numeric field overflow DETAIL: A field with precision 18, scale 12 must round to an absolute value less than 10^6.`

Here is the query that caused it:

```
INSERT INTO "asset__intrinsic_geometry" ("entity_id", "revision_id", "bundle", "delta", "langcode", "intrinsic_geometry_value", "intrinsic_geometry_geo_type", "intrinsic_geometry_lat", "intrinsic_geometry_lon", "intrinsic_geometry_left", "intrinsic_geometry_top", "intrinsic_geometry_right", "intrinsic_geometry_bottom", "intrinsic_geometry_geohash") VALUES ('566', '1189', 'plot', '0', 'en', '\x504f4c59474f4e2028282d3433343530362e3535343439393939383720363538303238312e3434323530303030332c202d3433343530342e383439383030303031383320363538303237332e3736383130303030312c202d3433343530312e3739303130303030303820363538303237342e3530303739393939392c202d3433343530332e353935313939393938343720363538303238322e3236393139393939372c202d3433343530362e3535343439393939383720363538303238312e3434323530303030332929', 'Polygon', '6580277.980145', '-434504.19009173', '-434506.5545', '6580282.2692', '-434501.7901', '6580273.7681', 'bpbpbpbpbpbp')
```

**Comment by mstenta** [comment]
The coordinates in that look like they are not using proper latitude/longitude:

> `'6580277.980145', '-434504.19009173'`

@aislinnpearson @paul121 I wonder if the particular GeoJSON file is the problem. Perhaps it has geometry that was created in a different coordinate system than WGS84?

**Comment by aislinnpearson** [comment]
Thank you @mstenta! It is as I suspected then - and possibly because we used ArcGIS rather than QGIS to generate these files. I'll have a word with Bruce and then close this issue if we find the problem there. Thank you!

**Comment by aislinnpearson** [comment]
Closing this issue as appears to be resolved

**Comment by aislinnpearson** [comment]
Hi @mstenta, @paul121,

So I figured out the problem with this file,. The GPS projection was ESPG 3857 (WGS84/ Pseudo-Meritor) where I think the experiment module only accepts ESPG 4326 (WGS84).

We are reviewing our GPS protocols at the moment. Currently everything is in ESPG 4326 (WGS84) because it is universal, but we are wondering if it needs to be more local. The other one we often use is ESPG 32360 (aka WGS84 30N). 

That is an ongoing internal discussion and I need to write some guidance to go with it _but_ I was wondering if there is a fundamental reason why it is only WGS84 in FarmOS, so re-opening this as 'for discussion' on Tuesday (no immediate need to do anything until we have resolved our internal conversations).

**Comment by mstenta** [comment]
> I was wondering if there is a fundamental reason why it is only WGS84 in FarmOS

Ultimately the reason "why" is because that is the default of most of the geodata dependencies that farmOS is built on, and there haven't been any requests to support others. It's been a looooong time since I looked into what is/isn't possible, but the core dependencies that we would need to examine are the [Geofield](https://www.drupal.org/project/geofield) module (which handles storing geometry data in the database) and the [OpenLayers](https://openlayers.org/) library (which handles rendering geometry data in a map).

I *believe* that OpenLayers supports different projections. I have vague memories of the Geofield module planning to support more than WGS84, but I do not know what the status of those efforts are (or if they are already done), so that might be the first place to look. The only thing I managed to find in their issue queues are:

- https://www.drupal.org/project/geofield/issues/3074575
- https://www.drupal.org/project/geofield/issues/1401446

Those are not very promising, nor are they very informative, though, so it might be worth doing some of our own investigating if this is of interest to Rothamsted.

**Comment by aislinnpearson** [comment]
We resolved this by uploading with the correct projection in the file

**Comment by aislinnpearson** [comment]
[Uploaded_RFF_plot_geometries.zip](https://github.com/user-attachments/files/16947755/Uploaded_RFF_plot_geometries.zip)

After discussing with @paul121  we agreed we would see if could create validation for these kinds of errors, which are essentially that the maps are in the wrong projection (not WGS84, ESPG: 4326)

**Comment by paul121** [comment]
Okay, so the unsupported CRS looks like this in the geojson:
```
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:EPSG::3857" } },
```

And the valid WGS84 in your existing geojson files looks like:
```
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
```

@aislinnpearson I'm curious how we want to handle this validation. I think there are a few options. I've currently implemented option 2:
1) Check if `EPSG::3857` is provided and raise an error. This seems like the most common and unsupported CRS you have uploaded
2) Check if a CRS is provided & raise an error if it is not WGS84 or EPSG 4326.
3) Always require that the CRS is provided & raise an error if is is not WGS84 or EPSG 4326. This might be tricky because I have seen many GeoJSON files that don't specify a CRS! But it seems that your programs are providing it consistently, so maybe this is OK.

**Comment by paul121** [comment]
Also to note this... :-)

https://github.com/CityScope/CS_choiceModels/issues/4#issuecomment-510554487
> CRS84 is NOT equivalent to EPSG:4326
> EPSG:4326 specifies coordinates in lat/long order and CRS:84 in long/lat order

I think we can support EPSG:4326 but it's important that this is specified in the CRS. If you have a file it would be good to test.

**Comment by aislinnpearson** [comment]
Following the call today we agreed that option 2 was the best. Paul had already implemented it.

> Check if a CRS is provided & raise an error if it is not WGS84 or EPSG 4326.
