### ISSUE TITLE
FarmOS 3.0: error creating boundaries

### ISSUE THREAD

**Issue by aislinnpearson** [Rothamsted-Ecoinformatics/farm_rothamsted#621]
Again, an issue I have raised with @paul121 but not documented: there is an error that appears when creating experiment boundaries. The boundary is created _but_ with the below errors, which also appear on the boundary itself.

![image](https://github.com/Rothamsted-Ecoinformatics/farm_rothamsted/assets/16349781/1bd79e32-31d6-4758-854e-888d9be75b0c)
![image](https://github.com/Rothamsted-Ecoinformatics/farm_rothamsted/assets/16349781/25821afa-5caf-45e3-ae88-41146ff6f26b)

**Comment by paul121** [comment]
Oh yep, I identified the bug from a dependency of farmOS core. See https://github.com/Rothamsted-Ecoinformatics/farm_rothamsted/issues/613#issuecomment-1942851688

We'll get this fixed in the next farmOS release. In the meantime I might turn down the verbosity of errors on the demo site. This error in particular wouldn't be visible in production as it is only a deprecation "warning" letting us know that in the future there may be a proper "error" that we need to fix.
