### ISSUE TITLE
Ontology Integration: Test new FarmOS Module

### ISSUE THREAD

**Issue by aislinnpearson** [Rothamsted-Ecoinformatics/farm_rothamsted#642]
Hi @mstenta, @paul121 

Once the Ontology module is ready to go, I was thinking it would be great to test it in our .dev account (so maybe an excuse to set that up as well - issue #611). Excited about showing it to Richard.

Our linked issue for the taxonomy is here: https://github.com/Rothamsted-Ecoinformatics/farm_rothamsted/issues/157

**Comment by mstenta** [comment]
@aislinnpearson Actually it will be part of core farmOS! Not a separate module. So assuming we settle on the details in the pull request and merge it before farmOS v3.2.0 is released, you'll get it on all your instances at the same time when we deploy that update. :-)

**Comment by mstenta** [comment]
(Oh but worth noting, the "Convention" module *is* a separate module, if you were interested in that too: https://github.com/mstenta/farm_convention)

**Comment by aislinnpearson** [comment]
@mstenta I've done all the testing for this and I love it. If I had one more request it would be to give names to links or to be able to tag them somehow. For example we may want to link them to Hestia _as well as_ the pesticides database _and_ an ontology term, in which case it would be nice to tag a link with that specific 'schema' (to use the word very loosely).

E.g. Triple superphosphate:

"Hestia": https://www.hestia.earth/term/tripleSuperPhosphateKgP2O5
"Agronomy ontology": http://purl.obolibrary.org/obo/AGRO_00002065

**Comment by mstenta** [comment]
@aislinnpearson This came up during the core discussions when we were adding this field. It makes sense! Now that the field was added to core, however, we are a bit constrained in making changes to it, because we have to assume that it is being used in the wild now, and we can't make "breaking changes" per our [semantic versioning](https://semver.org/) policy. So unfortunately we wouldn't be able to consider changing the field's data structure again until farmOS 4.x. :-/

I will add this to the "4.x wishlist" though! In the meantime, we could also consider adding additional Rothamsted-specific fields which have a more explicit meaning. But if it's not a high priority then maybe we can start planning the specifics for farmOS 4.x to be sure that it happens.
