### ISSUE TITLE
Quick Forms: Incorporating a single job which spans multiple days

### ISSUE THREAD

**Issue by aislinnpearson** [Rothamsted-Ecoinformatics/farm_rothamsted#82]
As described in the document attached to https://github.com/Rothamsted-Ecoinformatics/farm_rothamsted/issues/70#issue-1093250757: 

"For jobs which span multiple days fields like the tractor hours and fuel use need to be repeated over several days– for example if it starts raining or the equipment breaks and needs to be replaced. How does this integrate with logs applied over multiple areas though, if those jobs take multiple days?"

I have listed it as a new issue because some sections of the form because it relates to https://github.com/Rothamsted-Ecoinformatics/farm_rothamsted/issues/81#issuecomment-1004894373".

**Comment by aislinnpearson** [comment]
Following on from discussion on the 07 June (see #203) we agreed we would add an additional field on each quick form which allows you to pre-populate a quick form based on a previous record.

The features we were:

1. The option to pre-populate a quick form based on a previous record would appear on the setup tab for each quick form, under 'Plant Assets'. **It needs to be very clear to the user that they are creating a new log, not editing an existing log**
2. The user would be given a list of records to select from which are based on similar records from the same plant assets. **This might require tagging logs so that only harvest records appear under the harvest quick form, and only operations records appear under the Operations records (both currently observation logs), while Fertiliser logs only appear on the Fertiliser quick form and Spraying logs only appear on the Spraying quick form (both currently input logs). This might be related to the discussion in issue #160 
3. All fields will be editable but certain pre-determined fields in the quick form will appear blank and need to be re-entered as standard if selecting this option. Which fields appear as blank will depend on the quick form, and we will need to create a separate issue for this relating to each quick form.

**Comment by paul121** [comment]
> The option to pre-populate a quick form based on a previous record would appear on the setup tab for each quick form, under 'Plant Assets'.

This is proving to be a bit more difficult than I first thought. Adding some `AJAX` to this area is not an easy task and feels quite prone to failure even if I was able to figure something out.

Instead, I'd like to propose we add a big "Prepopulate" or "Clone" button that opens previous log submissions in a modal. This provides 3 general features:

1. Display options in familiar table view of logs that lets users filter by not only the plant asset, but location, time range, status, assigned user, etc (as much or as little as we want).
2. Support future use cases of "jobs which span multiple days" where you might not prepopulate based on the plant asset, but the field location or assigned user.
3. Can also provide the same log view in a dedicated page to see "Log submissions" that were created by the quick form eg: `/quick/trailer_harvest/logs`

> **It needs to be very clear to the user that they are creating a new log, not editing an existing log**

The downside to this approach is that the "prepopulate" step does not happen "in-line" with the completing the quick form, instead it requires a click on the "prepopulate" button. I think this additional click to "Prepopulate" is worth the effort because it forces the user to complete the quick form with the "prepopulate" intention, not "edit an existing" log. I believe this helps with another issue we discussed where data that is entered to the quick form *before prepopulating* would be lost when the form is re-loaded & prepopulated.

Here are some example screenshots (still working on "Copy" or "Prepopulate" language?):
![form_bare](https://user-images.githubusercontent.com/3116995/175427835-6bc1caba-f519-42ec-94b2-7761865a79cc.png)
![form_prepopulate_modal](https://user-images.githubusercontent.com/3116995/175427838-85bb7238-774f-47fd-bc19-2bf148e7faa9.png)

I have more work to do on the actual prepopulating logic itself.. but we can think about the UI aspect of this in the meantime @aislinnpearson

**Comment by paul121** [comment]
Agh there is an annoying bug where the title of this "modal" is "Array". Relevant core issue is here, seems to be stuck: https://www.drupal.org/project/drupal/issues/2663316

This wouldn't be as big of an issue but it does log a "notice` log each time the modal is opened :roll_eyes:

**Comment by aislinnpearson** [comment]
Hi @paul121,

Apologies. Bit behind on all of my replies as usual. 

> This is proving to be a bit more difficult than I first thought. Adding some AJAX to this area is not an easy task and feels quite prone to failure even if I was able to figure something out. Instead, I'd like to propose we add a big "Prepopulate" or "Clone" button that opens previous log submissions in a modal

The opening of the dialogue box sounds like our only real option if the AJAX is prone to failure, so lets go for that. :) 

> I have more work to do on the actual prepopulating logic itself.. but we can think about the UI aspect of this in the meantime

 I feel like we (I) have given this so little thought that if initially it is only an exact copy of the old quick form we could start there and see what user feedback/ errors we get.

> Agh there is an annoying bug where the title of this "modal" is "Array". Relevant core issue is here, seems to be stuck

I can't tell how much of a barrier this is so let's discuss it on Tuesday. Worse case scenario we can leave it out of the next release - I think changing the question set will have solved a large part of the issue on farm for harvest, and we can come back to this later as it is more relevant to spraying and fertiliser spreading...

**Comment by paul121** [comment]
No worries @aislinnpearson ! I've implemented this initial view of log submissions. It will work for any quick form at the path `/quick/{quick_form_id}/logs`, but only the Trailer harvest quick form will have the "Prepopulate" button visible.

> Agh there is an annoying bug where the title of this "modal" is "Array". 

Sorry I didn't comment back here, but I was able to get this working another way! Just wanted to mention the drupal issue here so it will be easier to find later on. I also included a comment with a link to the issue in the relevant code to help us understand this hack in the future.
